language: elixir
elixir: '1.5.2'
cache:
  directories:
    - _build
    - deps

services:
  - mysql

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
